### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by MajuTo**
Added the French translation strings (fr_FR) to the project and made the locale available.

Thx for your work

### CODE REVIEW

**Comment by juliorosseti** [comment]
Welcome @MajuTo!

Thanks for your feedback to the plugin and also for your contribution,
I'm very grateful!

**Comment by juliorosseti** [comment]
Published version `1.0.6` on npm with new locale!

**Comment by nioperas06** [comment]
Hey @juliorosseti, great job on this plugin. How can I use this locale or any locale available in my app?

**Comment by juliorosseti** [comment]
> Hey @juliorosseti, great job on this plugin. How can I use this locale or any locale available in my app?

Hi @nioperas06!

Tks!!

I have been trying to do this and I believe it has not been implemented, I will work to fix this.

**Pull request merged**
